<?php

namespace Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VehicleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepositoryRepository extends EntityRepository
{

    /**
     * @return Doctrine\ORM\QueryBuilder
     */
    public function getItemsQuery()
    {
        return $this->createQueryBuilder("v")
                        ->where("v.enabled = :enabled")->setParameter("enabled", 1)
                        ->orderBy("v.title", "ASC");
    }

    /**
     * @return Doctrine\ORM\QueryBuilder
     */
    public function getByCategory($category)
    {
        $query = $this->getItemsQuery();

        return $query->andWhere("t.category = :category")->setParameter("category", $category);
    }

    /**
     * @return Doctrine\ORM\QueryBuilder
     */
    public function getByTypeSlug($type)
    {
        $query = $this->getItemsQuery();

        return $query->andWhere("t.slug = :type")->setParameter("type", $type);
    }

}
